### ISSUE TITLE
Getting Property 'as_group' not found error when trying to get Order

### ISSUE THREAD

**Issue by catchnaresh** [cryovat/gengo-dotnet#5]
Hello,

Thanks for the library. It's very much useful.

I am getting a strange issue when I am trying to get Order from Gengo.

Same block of code is working fine with Gengo sandbox environment. But it's giving the issue when I try to use Gengo production environment. Is that something already known? 

Thanks.
Naresh

**Comment by cryovat** [comment]
Thank you for catching this, it looks like they've changed the API and removed the as_group property from the response.

I've pushed an [updated version](https://www.nuget.org/packages/gengo-dotnet/0.9.6) to NuGet that doesn't try to read the property, I hope this solves the problem. :smiley:

Let me know if you run into any additional trouble.

**Comment by thandunaresh** [comment]
Thanks Jarl Erik Schmidt. It was quick.

It's working fine now.

I will let you know if I come across any issue. I don't mind contributing to this project. Please let me know if you need anything on this.

Thanks again.
